# Generated by Django 5.0.6 on 2026-05-28 10:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('telegram_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('language', models.CharField(default='uz', max_length=5)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'voices_botuser',
            },
        ),
        migrations.CreateModel(
            name='Voice',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('file_id', models.CharField(max_length=255)),
                ('file_unique_id', models.CharField(max_length=255)),
                ('description', models.TextField(db_index=True)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('is_public', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voices', to='voices.botuser')),
            ],
            options={
                'db_table': 'voices_voice',
                'indexes': [models.Index(fields=['file_unique_id'], name='voices_voic_file_un_f78fc8_idx'), models.Index(fields=['usage_count'], name='voices_voic_usage_c_140f4d_idx'), models.Index(fields=['created'], name='voices_voic_created_2a033d_idx'), models.Index(fields=['is_public'], name='voices_voic_is_publ_3ab73a_idx'), models.Index(fields=['is_active'], name='voices_voic_is_acti_433805_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='voice',
            constraint=models.UniqueConstraint(fields=('owner', 'file_unique_id'), name='unique_voice_per_user'),
        ),
    ]
